---
title: "EDA"
format: html
editor: visual
---

# EDA

## Our Dataset
*briefly describe the data and the variables you have to work with (just discuss the ones you’ll investigate/use in your analysis).*

## Purpose
*describe the purpose of your EDA and ultimate goal of modeling.*

## Importing the Data + Initial Data Processing

```{r}
#| output: false

# import libraries
library(readr)
library(tidyr)
library(dplyr)
```


```{r}
# read in the data
df <- readr::read_csv("diabetes_binary_health_indicators_BRFSS2015.csv")
head(df)

# rename columns and update datatypes/data storage
df <- df |>
  rename(Diabetes=Diabetes_binary) |>
  mutate(Diabetes=case_when(
    Diabetes==0 ~ "no diabetes",
    Diabetes==1 ~ "prediabetes", 
    Diabetes==2 ~ "diabetes")) |>
  mutate(Diabetes=as.factor(Diabetes)) |>
  
  rename(High_BP=HighBP) |>
  mutate(High_BP=case_when(
    High_BP==0 ~ "no",
    High_BP==1 ~ "yes")) |>
  mutate(High_BP=as.factor(High_BP)) |>
  
  rename(High_Cholesterol=HighChol) |>
  mutate(High_Cholesterol=case_when(
    High_Cholesterol==0 ~ "no",
    High_Cholesterol==1 ~ "yes")) |>
  mutate(High_Cholesterol=as.factor(High_Cholesterol)) |>
  
  rename(Checked_Cholesterol_5years=CholCheck) |>
  mutate(Checked_Cholesterol_5years=case_when(
    Checked_Cholesterol_5years==0 ~ "no",
    Checked_Cholesterol_5years==1 ~ "yes")) |>
  mutate(Checked_Cholesterol_5years=as.factor(Checked_Cholesterol_5years)) |>
  
  mutate(Smoker=case_when(
    Smoker==0 ~ "no",
    Smoker==1 ~ "yes")) |>
  mutate(Smoker=as.factor(Smoker)) |>
  
  mutate(Stroke=case_when(
    Stroke==0 ~ "no",
    Stroke==1 ~ "yes")) |>
  mutate(Stroke=as.factor(Stroke)) |>
  
  mutate(HeartDiseaseorAttack=case_when(
    HeartDiseaseorAttack==0 ~ "no",
    HeartDiseaseorAttack==1 ~ "yes")) |>
  mutate(HeartDiseaseorAttack=as.factor(HeartDiseaseorAttack)) |>
  
  rename(Physical_Activity_30days=PhysActivity) |>
  mutate(Physical_Activity_30days=case_when(
    Physical_Activity_30days==0 ~ "no",
    Physical_Activity_30days==1 ~ "yes")) |>
  mutate(Physical_Activity_30days=as.factor(Physical_Activity_30days)) |>
  
  rename(Daily_Fruit=Fruits) |>
  mutate(Daily_Fruit=case_when(
    Daily_Fruit==0 ~ "no",
    Daily_Fruit==1 ~ "yes")) |>
  mutate(Daily_Fruit=as.factor(Daily_Fruit)) |>
  
  rename(Daily_Vegetable=Veggies) |>
  mutate(Daily_Vegetable=case_when(
    Daily_Vegetable==0 ~ "no",
    Daily_Vegetable==1 ~ "yes")) |>
  mutate(Daily_Vegetable=as.factor(Daily_Vegetable)) |>
  
  rename(Heavy_Alcohol_Consumption=HvyAlcoholConsump) |>
  mutate(Heavy_Alcohol_Consumption=case_when(
    Heavy_Alcohol_Consumption==0 ~ "no",
    Heavy_Alcohol_Consumption==1 ~ "yes")) |>
  mutate(Heavy_Alcohol_Consumption=as.factor(Heavy_Alcohol_Consumption)) |>
  
  rename(Has_Healthcare=AnyHealthcare) |>
  mutate(Has_Healthcare=case_when(
    Has_Healthcare==0 ~ "no",
    Has_Healthcare==1 ~ "yes")) |>
  mutate(Has_Healthcare=as.factor(Has_Healthcare)) |>
  
  rename(No_Doctor_bc_Cost=NoDocbcCost) |>
  mutate(No_Doctor_bc_Cost=case_when(
    No_Doctor_bc_Cost==0 ~ "no",
    No_Doctor_bc_Cost==1 ~ "yes")) |>
  mutate(No_Doctor_bc_Cost=as.factor(No_Doctor_bc_Cost)) |>
  
  rename(General_Health=GenHlth) |>
  mutate(General_Health=case_when(
    General_Health==1 ~ "exellent",
    General_Health==2 ~ "very good",
    General_Health==3 ~ "good",
    General_Health==4 ~ "fair",
    General_Health==5 ~ "poor")) |>
  mutate(General_Health=as.factor(General_Health)) |>
  
  rename(Bad_Mental_Days_of_Past_30=MentHlth) |>
  rename(Bad_Physical_Days_of_Past_30=PhysHlth) |>
  
    
  rename(Difficulty_Walking=DiffWalk) |>
  mutate(Difficulty_Walking=case_when(
    Difficulty_Walking==0 ~ "no",
    Difficulty_Walking==1 ~ "yes")) |>
  mutate(Difficulty_Walking=as.factor(Difficulty_Walking)) |>
  
  mutate(Sex=case_when(
    Sex==0 ~ "female",
    Sex==1 ~ "male")) |>
  mutate(Sex=as.factor(Sex)) |>

  mutate(Age=case_when(
    Age==1 ~ "18-24",
    Age==2 ~ "25-29",
    Age==3 ~ "30-34",
    Age==4 ~ "35-39",
    Age==5 ~ "40-44",
    Age==6 ~ "45-49",
    Age==7 ~ "50-54",
    Age==8 ~ "55-59",
    Age==9 ~ "60-64",
    Age==10 ~ "65-69",
    Age==11 ~ "70-74",
    Age==12 ~ "75-79",
    Age==13 ~ "80 or older")) |>
  mutate(Age=as.factor(Age)) |>
  
  rename(Highest_Education_Achieved=Education) |>
  mutate(Highest_Education_Achieved=case_when(
    Highest_Education_Achieved==1 ~ "kindergarten",
    Highest_Education_Achieved==2 ~ "1st-8th grade",
    Highest_Education_Achieved==3 ~ "9th-11th grade",
    Highest_Education_Achieved==4 ~ "12th grade or GED",
    Highest_Education_Achieved==5 ~ "1-3 years college",
    Highest_Education_Achieved==6 ~ "4+ years college")) |>
  mutate(Highest_Education_Achieved=as.factor(Highest_Education_Achieved)) |>

  mutate(Income=case_when(
    Income==1 ~ "less than $10,000",
    Income==2 ~ "less than $15,000",
    Income==3 ~ "less than $20,000",
    Income==4 ~ "less than $25,000",
    Income==5 ~ "less than $35,000",
    Income==6 ~ "less than $50,000",
    Income==7 ~ "less than $75,000",
    Income==8 ~ "more than $75,000")) |>
  mutate(Income=as.factor(Income))

head(df)
```

```{r}
# look at unique values (validation!)


# look at outliers of numerical data (validation!)
# convert factor vars and use meaningful names
# address other datatype issues
# check for missingness
```


## Data Summaries

```{r}
# **do not split data into train/test yet!
# summary stats + plots (especially as vars relate to response)
# univariate measures/graphs
# multivariate measures/graphs
```



[Click here for the Modeling Page](Modeling.html)
